/*
 * SPDX-FileCopyrightText: 2025 CESSDA ERIC (support@cessda.eu)
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *    http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package eu.cessda.fairtests.dto;

import java.io.InputStream;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.UUID;

import org.springframework.core.io.ClassPathResource;
import org.yaml.snakeyaml.Yaml;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import eu.cessda.fairtests.Result;

@JsonPropertyOrder({
    "@context",
    "@id",
    "@type",
    "identifier",
    "title",
    "description",
    "license",
    "value",
    "completion",
    "assessmentTarget",
    "log",
    "outputFromTest",
    "generatedAtTime",
    "wasGeneratedBy"
})
public class TestResult {

    @JsonProperty("@context")
    private String context = "https://w3id.org/ftr/context";

    @JsonProperty("@id")
    private String id;

    @JsonProperty("@type")
    private String type = "https://w3id.org/ftr#TestResult";

    private String identifier;

    private String testName;
    
    private String title;
    private String description;
    private String testEndpoint = "https://fair-tests.cessda.eu/assess/test/";

    private License license;
    private String value;

    private Completion completion;

    @JsonProperty("assessmentTarget")
    private AssessmentTarget assessmentTarget;

    private String log;

    @JsonProperty("outputFromTest")
    private OutputFromTest outputFromTest;

    @JsonProperty("generatedAtTime")
    private GeneratedAtTime generatedAtTime;

    @JsonProperty("wasGeneratedBy")
    private WasGeneratedBy wasGeneratedBy;

    /**
     * Constructs a TestResult object with the given test name, resource URL, and test value.
     * The constructor generates a unique URN for the test result, sets the title and
     * description based on the test name, and initializes other fields such as license,
     * completion percentage, assessment target, log, output from test, generated at time,
     * and was generated by information.  
     * 
     * @param testName the name of the test that was run, used to set the title and
     * description of the test result
     * @param resourceUrl the URL of the resource that was assessed, used to set the assessment target 
     * and 'was generated by' information
     * @param result the result of the test, typically an enum value representing the outcome,
     * used to set the value field of the test result
     */
    public TestResult(String name, String resourceUrl, Result result) {
        String urn = "urn:cessda:" + UUID.randomUUID().toString();
        this.id = urn;
        this.identifier = urn;  // identifier should match @id
        this.testName = name;
        this.value = result.toString();
        this.log = getLogMessage(result);
        this.title = "Output from running test: " + name +
                " (https://fair-tests.cessda.eu/assess/test/" + name + ")";
        this.license = new License("http://creativecommons.org/licenses/by/4.0/");
        this.completion = new Completion(getCompletionPercentage(result));
        this.assessmentTarget = new AssessmentTarget(resourceUrl);
        this.outputFromTest = new OutputFromTest("https://fair-tests.cessda.eu/assess/test/" + testName);
        this.generatedAtTime = new GeneratedAtTime();
        this.wasGeneratedBy = new WasGeneratedBy(resourceUrl, name, this);
        this.description = wasGeneratedBy.getWasAssociatedWith().getDescription();
    }


    /**
     * Helper method
     * @param result
     * @return
     */
    private int getCompletionPercentage (Result result) {
        switch (result) {
            case PASS:
                return 100;
            case FAIL:
                return 100;
            case INDETERMINATE:
                return 0;
            default:
                return 0;
        }
    }


    /**
     * Helper method to generate a log message based on the test result.
     * This method takes a Result enum value as input
     * 
     * @param result the result of the test, typically an enum value representing the outcome
     * @return a log message string that describes the outcome of the test based on the provided result
     */
    private String getLogMessage (Result result) {
        switch (result) {
            case PASS:
                return "Test passed successfully.";
            case FAIL:
                return "Test failed.";
            case INDETERMINATE:
                return "Test result is indeterminate.";
            default:
                return "Unknown test result.";
        }
    }

    // Getters and setters
    public String getContext() {
        return context;
    }

    public void setContext(String context) {
        this.context = context;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
        this.identifier = id;  // Keep identifier in sync with id
    }

    public String getIdentifier() {
        return identifier;
    }

    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @JsonIgnore
    public String getTestName() {
        return testName;
    }

    public void setTestName(String testName) {
        this.testName = testName;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public License getLicense() {
        return license;
    }

    public void setLicense(License license) {
        this.license = license;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Completion getCompletion() {
        return completion;
    }

    public void setCompletion(Completion completion) {
        this.completion = completion;
    }

    public AssessmentTarget getAssessmentTarget() {
        return assessmentTarget;
    }

    public void setAssessmentTarget(AssessmentTarget assessmentTarget) {
        this.assessmentTarget = assessmentTarget;
    }

    public String getLog() {
        return log;
    }

    public void setLog(String log) {
        this.log = log;
    }

    public OutputFromTest getOutputFromTest() {
        return outputFromTest;
    }

    public void setOutputFromTest(OutputFromTest outputFromTest) {
        this.outputFromTest = outputFromTest;
    }

    public GeneratedAtTime getGeneratedAtTime() {
        return generatedAtTime;
    }

    public void setGeneratedAtTime(GeneratedAtTime generatedAtTime) {
        this.generatedAtTime = generatedAtTime;
    }

    public WasGeneratedBy getWasGeneratedBy() {
        return wasGeneratedBy;
    }

    public void setWasGeneratedBy(WasGeneratedBy wasGeneratedBy) {
        this.wasGeneratedBy = wasGeneratedBy;
    }

    // Nested classes
    public static class License {
        @JsonProperty("@id")
        private String id;

        public License(String id) {
            this.id = id;
        }

        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }
    }

    @JsonPropertyOrder({
        "@value"
    })
    public static class Completion {
        @JsonProperty("@value")
        private int value;

        public Completion(int value) {
            this.value = value;
        }

        public int getValue() {
            return value;
        }

        public void setValue(int value) {
            this.value = value;
        }
    }

    public static class AssessmentTarget {
        @JsonProperty("@id")
        private String id;

        public AssessmentTarget(String id) {
            this.id = id;
        }

        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }
    }

    @JsonPropertyOrder({
        "@id",
        "@type"
    })
    public static class OutputFromTest {
        @JsonProperty("@id")
        private String id;

        @JsonProperty("@type")
        private String type = "Test";

        public OutputFromTest(String id) {
            this.id = id;
        }

        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }

        public String getType() {
            return type;
        }

        public void setType(String type) {
            this.type = type;
        }
    }

    @JsonPropertyOrder({
        "@type",
        "@value"
    })
    public static class GeneratedAtTime {
        @JsonProperty("@type")
        private String type = "http://www.w3.org/2001/XMLSchema#date";

        @JsonProperty("@value")
        private String value;

        public GeneratedAtTime() {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("EEE MMM dd HH:mm:ss z yyyy", Locale.ENGLISH);
            this.value = ZonedDateTime.now().format(formatter);
        }

        public String getType() {
            return type;
        }

        public void setType(String type) {
            this.type = type;
        }

        public String getValue() {
            return value;
        }

        public void setValue(String value) {
            this.value = value;
        }
    }

    @JsonPropertyOrder({
        "@type",
        "used",
        "wasAssociatedWith"
    })
    public static class WasGeneratedBy {
        @JsonProperty("@type")
        private String type = "TestExecutionActivity";

        private Used used;

        @JsonProperty("wasAssociatedWith")
        private WasAssociatedWith wasAssociatedWith;

        public WasGeneratedBy(String resourceUrl, String testName, TestResult result) {
            this.used = new Used(resourceUrl);
            this.wasAssociatedWith = new WasAssociatedWith(testName, result);
        }

        public String getType() {
            return type;
        }

        public void setType(String type) {
            this.type = type;
        }

        public Used getUsed() {
            return used;
        }

        public void setUsed(Used used) {
            this.used = used;
        }

        public WasAssociatedWith getWasAssociatedWith() {
            return wasAssociatedWith;
        }

        public void setWasAssociatedWith(WasAssociatedWith wasAssociatedWith) {
            this.wasAssociatedWith = wasAssociatedWith;
        }
    }

    public static class Used {
        @JsonProperty("@id")
        private String id;

        public Used(String id) {
            this.id = id;
        }

        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }
    }

    @JsonPropertyOrder({
        "@id",
        "identifier",
        "title",
        "description",
        "endpointDescription",
        "endpointURL"
    })
    public static class WasAssociatedWith {
        @JsonProperty("@id")
        private String id;

        private String identifier;
        private String title;
        private String apiDescription = "https://fair-tests.cessda.eu/api/";
        private String description;

        @JsonProperty("endpointDescription")
        private EndpointDescription endpointDescription;

        @JsonProperty("endpointURL")
        private EndpointURL endpointURL;

        public WasAssociatedWith(String testName, TestResult result) {
            this.id = result.testEndpoint + testName;
            this.identifier = this.id;
            this.title = getTestTitle(testName);
            this.description = getTestDescription(testName);
            this.endpointDescription = new EndpointDescription(
                    apiDescription + testName + ".ttl");
            this.endpointURL = new EndpointURL(result.testEndpoint + testName);
        }

        /**
         * Helper method to load test metadata from the corresponding Turtle
         * file for the given test name. This method attempts to read the
         * Turtle file associated with the test, extract the title and
         * description from the file's content, and return them as a map.
         * If the file does not exist or cannot be read, it returns default
         * metadata based on the test name.    
         * 
         * @param testName the name of the test for which to load metadata
         * @return a map containing the title and description of the test,
         *         either loaded from the Turtle file or generated based on
         *         the test name if the file is not available.    
         */
        private Map<String, String> loadTestMetadata(String testName) {
            Map<String, String> metadata = new HashMap<>();
            metadata.put("title", "Test: " + testName);
            metadata.put("description", "This test verifies " + testName);

            try {
                String filename = testName + ".ttl";
                ClassPathResource resource = new ClassPathResource("static/" + filename);

                if (!resource.exists()) {
                    return metadata;
                }

                Yaml yaml = new Yaml();
                try (InputStream inputStream = resource.getInputStream()) {
                    Map<String, Object> data = yaml.load(inputStream);

                    // Safe extraction using helper method
                    String title = extractStringValue(data, "info", "title");
                    if (title != null) {
                        metadata.put("title", title);
                    }

                    String description = extractStringValue(data, "info", "description");
                    if (description != null) {
                        metadata.put("description", description);
                    }
                }

            } catch (Exception e) {
                e.printStackTrace();
            }

            return metadata;
        }

        /**
         * Safely extract a nested string value from a map structure
         * given a sequence of keys. This method traverses the map
         * using the provided keys, checking at each step whether the
         * current value is a map and whether the next key exists.
         * 
         * @param map the map from which to extract the value
         * @param keys the sequence of keys to navigate through the map
         * @return the extracted string value if found, or null if any
         *         key is missing or if the final value is not a string
         */
        private String extractStringValue(Map<String, Object> map, String... keys) {
    Object current = map;

    for (String key : keys) {
        if (!(current instanceof Map)) {
            return null;
        }
        current = ((Map<?, ?>) current).get(key);
        if (current == null) {
            return null;
        }
    }
    
    if (current instanceof String) {
        String value = (String) current;
        // Strip leading and trailing quotes if present
        if (value.startsWith("\"") && value.endsWith("\"") && value.length() > 1) {
            return value.substring(1, value.length() - 1);
        }
        return value;
    }
    
    return null;
}

        /**
         * Helper method to load test metadata from the
         * corresponding Turtle file for the given test name.
         * This method attempts to read the Turtle file associated with the test,
         * extract the title and description from the file's content, and return them as
         * a map.
         * If the file does not exist or cannot be read, it returns default metadata
         * based on the test name.
         * 
         * @param testName the name of the test for which to load metadata
         * @return a map containing the title and description of the test,
         *         either loaded from the Turtle file or generated based on the test
         *         name if the file is not available
         */
        private String getTestTitle(String testName) {
            return loadTestMetadata(testName).get("title");
        }

        /**
         * Helper method to load the test description from the
         * corresponding Turtle file for the given test name.
         * This method uses the loadTestMetadata method to retrieve the description,
         * which may be extracted from the Turtle file or generated based on the
         * test name if the file is not available.
         *
         * @param testName the name of the test for which to load the description
         * @return the description of the test, either loaded from the Turtle file
         *         or generated based on the test name if the file is not available
         */
        private String getTestDescription(String testName) {
            return loadTestMetadata(testName).get("description");
        }

        // Getters and setters
        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
            this.identifier = id;  // Keep identifier in sync with id
        }

        public String getIdentifier() {
            return identifier;
        }

        public void setIdentifier(String identifier) {
            this.identifier = identifier;
        }

        public String getTitle() {
            return title;
        }

        public void setTitle(String title) {
            this.title = title;
        }

        public String getDescription() {
            return description;
        }

        public void setDescription(String description) {
            this.description = description;
        }

        public EndpointDescription getEndpointDescription() {
            return endpointDescription;
        }

        public void setEndpointDescription(EndpointDescription endpointDescription) {
            this.endpointDescription = endpointDescription;
        }

        public EndpointURL getEndpointURL() {
            return endpointURL;
        }

        public void setEndpointURL(EndpointURL endpointURL) {
            this.endpointURL = endpointURL;
        }
    }

    public static class EndpointDescription {
        @JsonProperty("@id")
        private String id;

        public EndpointDescription(String id) {
            this.id = id;
        }

        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }
    }

    public static class EndpointURL {
        @JsonProperty("@id")
        private String id;

        public EndpointURL(String id) {
            this.id = id;
        }

        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }
    }
}
